const vscode = require('vscode');
const path = require('path');
const { logger } = require('../utils/logger');
const { t } = require('../utils/i18n');

/**
 * Checks if a file exists using VS Code's FS API
 */
async function exists(uri) {
    try {
        await vscode.workspace.fs.stat(uri);
        return true;
    } catch {
        return false;
    }
}

/**
 * Safely copies a file from the shadow cage to the real workspace using VS Code FS.
 * Also performs the .ts -> .js literal replacement for Safe-Web output.
 */
async function extractFile(shadowUri, targetUri, isBundleFinal = false, manifest = null, addWatermark = false, sourceRefPath = null) {
    if (!(await exists(shadowUri))) return false;


    // Read the shadow file via vscode fs (returns Uint8Array)
    let contentBytes = await vscode.workspace.fs.readFile(shadowUri);

    // If this is the final JS bundle, do the magical string replacement 
    // strictly for the dependencies listed in the Manifest.
    if (isBundleFinal && manifest && targetUri.fsPath.endsWith('.js')) {
        let contentStr = Buffer.from(contentBytes).toString('utf8');
        let modified = false;

        // "Paso 5: El Reemplazo Quirúrgico"
        // Replace exact raw external strings safely without wild regex
        manifest.externals.forEach(ext => {
            if (ext.isTs) {
                const targetStr = ext.raw.replace(/\.ts$/, '.js');
                // Target literal string imports (e.g. "../_afuera.ts")
                const searchStr = `"${ext.raw}"`;
                const searchStr2 = `'${ext.raw}'`;
                
                if (contentStr.includes(searchStr)) {
                    contentStr = contentStr.split(searchStr).join(`"${targetStr}"`);
                    modified = true;
                }
                if (contentStr.includes(searchStr2)) {
                    contentStr = contentStr.split(searchStr2).join(`'${targetStr}'`);
                    modified = true;
                }
            }
        });

        if (modified) {
            contentBytes = Buffer.from(contentStr, 'utf8');
        }
    }

    // "Paso 6: El Sello del Herrero" (Watermark)
    if (addWatermark) {
        let contentStr = Buffer.from(contentBytes).toString('utf8');
        let watermark = `/** @generated by Forge TypeLayer - DO NOT EDIT DIRECTLY */\n`;
        if (sourceRefPath) {
            watermark += `/// <reference path="./${path.basename(sourceRefPath)}" />\n`;
        }
        
        if (!contentStr.includes('@generated by Forge TypeLayer')) {
            contentStr = watermark + contentStr;
            contentBytes = Buffer.from(contentStr, 'utf8');
        }
    }

    // Write gracefully to target so VS Code File Explorer syncs natively
    await vscode.workspace.fs.writeFile(targetUri, contentBytes);
    return true;
}

/**
 * Orchestrates the extraction of the Main file, its inline helpers, 
 * and external parent helpers based on the Manifest.
 */
async function performExtraction(forgeContext, shadowDir, entryFile, manifestDataMap, strategy = null) {
    const ForgeContext = require('../context');
    const actualStrategy = strategy || forgeContext.currentBatchStrategy || (forgeContext.STRATEGY ? forgeContext.STRATEGY.STANDALONE : ForgeContext.STRATEGY.STANDALONE);
    
    const relEntry = path.relative(forgeContext.projectRoot, entryFile);

    logger.debug(`[Extractor] Entry: ${entryFile}`);
    logger.debug(`[Extractor] Relative entry: ${relEntry}`);
    
    // Strip ALL known lock suffixes, not just .ts fallback
    // We can't use the lockSuffixes list here yet (too early in the function),
    // so we strip from last dot-segment that matches our convention pattern.
    // The actual suffix lookup happens below in resolveLockSuffixMapping().
    // For the base, we simply strip the ts/mts extension portion after the last dot.
    const entryBaseNoExt = relEntry.replace(/\.[^.]+\.m?ts$|\.m?ts$/, '');
    logger.debug(`[Extractor] Base (no ext): ${entryBaseNoExt}`);

    // ── Suffix Resolution ──────────────────────────────────────────────────────
    // lockSuffixes are the authoring file markers: .source.ts, .forge.ts, .f.ts,
    // .source.mts, .forge.mts, .f.mts — and any user-defined custom ones.
    // On deploy, we strip the entire infix marker and keep only the base extension.
    //
    // Examples:
    //   algo.source.ts  → shadow: algo.source.js  → target: algo.js
    //   algo.forge.ts   → shadow: algo.forge.js   → target: algo.js
    //   algo.f.ts       → shadow: algo.f.js       → target: algo.js
    //   algo.source.mts → shadow: algo.source.mjs → target: algo.mjs
    const DEFAULT_LOCK_SUFFIXES = ['.f.ts', '.forge.ts', '.source.ts', '.f.mts', '.forge.mts', '.source.mts'];
    const lockSuffixes = forgeContext.lockSuffixes || DEFAULT_LOCK_SUFFIXES;

    /**
     * Given a relative entry filename, finds the matching lockSuffix (if any)
     * and returns both the shadow filename and the stripped target filename.
     * Returns null if not a lock-convention file.
     */
    function resolveLockSuffixMapping(relPath) {
        for (const suffix of lockSuffixes) {
            if (relPath.endsWith(suffix)) {
                const isMts    = suffix.endsWith('.mts');
                const baseExt  = isMts ? '.mts' : '.ts';
                const outExt   = isMts ? '.mjs' : '.js';
                const infix    = suffix.slice(0, suffix.lastIndexOf('.')); // '.source', '.forge', '.f'

                // TSC always emits '.d.ts' declaration files regardless of input ext
                const shadowDtsSuffix = infix + '.d.ts';
                // Target declaration type follows ESM convention: .mts → .d.mts, .ts → .d.ts
                const targetDtsSuffix = isMts ? '.d.mts' : '.d.ts';

                return {
                    matched: true,
                    shadowJsSuffix:  infix + outExt,    // what TSC/Bun emits in shadow
                    shadowDtsSuffix,                    // TSC always uses .d.ts
                    targetJsSuffix:  outExt,            // stripped: .js or .mjs
                    targetDtsSuffix                     // stripped: .d.ts or .d.mts
                };
            }
        }
        // Not a lock-convention file — regular .ts → .js / .mts → .mjs
        const isMts = relPath.endsWith('.mts');
        return {
            matched: false,
            shadowJsSuffix:  isMts ? '.mjs' : '.js',
            shadowDtsSuffix: '.d.ts',    // TSC always emits .d.ts
            targetJsSuffix:  isMts ? '.mjs' : '.js',
            targetDtsSuffix: isMts ? '.d.mts' : '.d.ts'
        };
    }

    const suffixMap = resolveLockSuffixMapping(relEntry);
    logger.debug(`[Extractor] Suffix map: shadow=${suffixMap.shadowJsSuffix}, target=${suffixMap.targetJsSuffix}, matched=${suffixMap.matched}`);

    const shadowMainJs  = vscode.Uri.file(path.join(shadowDir, entryBaseNoExt + suffixMap.shadowJsSuffix));
    const targetMainJs  = vscode.Uri.file(path.join(forgeContext.projectRoot, entryBaseNoExt + suffixMap.targetJsSuffix));
    
    const shadowMainDts = vscode.Uri.file(path.join(shadowDir, entryBaseNoExt + suffixMap.shadowDtsSuffix));
    const targetMainDts = vscode.Uri.file(path.join(forgeContext.projectRoot, entryBaseNoExt + suffixMap.targetDtsSuffix));

    logger.debug(`[Extractor] Shadow JS:  ${shadowMainJs.fsPath}`);
    logger.debug(`[Extractor] Target JS:  ${targetMainJs.fsPath}`);
    logger.debug(`[Extractor] Shadow DTS: ${shadowMainDts.fsPath}`);
    logger.debug(`[Extractor] Target DTS: ${targetMainDts.fsPath}`);

    const manifest = manifestDataMap[entryFile] || { externals: [], inlines: [] };
    const entryDir = path.dirname(entryFile);

    let extractedCount = 0;

    // 1. Extract Main File (Bundle) + Types
    const jsExists = await exists(shadowMainJs);
    const dtsExists = await exists(shadowMainDts);
    logger.debug(`[Extractor] Shadow JS exists: ${jsExists}, Shadow DTS exists: ${dtsExists}`);

    if (jsExists) {
        await extractFile(shadowMainJs, targetMainJs, true, manifest, forgeContext.addWatermark, entryFile);
        logger.debug(`[Extractor] ✅ Extracted main JS → ${targetMainJs.fsPath}`);
        extractedCount++;
    } else {
        logger.debug(`[Extractor] ❌ Main JS NOT FOUND in shadow: ${shadowMainJs.fsPath}`);
    }

    if (dtsExists) {
        await extractFile(shadowMainDts, targetMainDts, false, null, forgeContext.addWatermark, entryFile);
        logger.debug(`[Extractor] ✅ Extracted main DTS → ${targetMainDts.fsPath}`);
        extractedCount++;
    } else {
        logger.debug(`[Extractor] ❌ Main DTS NOT FOUND in shadow: ${shadowMainDts.fsPath}`);
    }

    // 2. Recursive/Hybrid Extraction: Extract Inlines and Externals JS if strategy demands it
    const shouldExtractDependencies = actualStrategy === (forgeContext.STRATEGY?.RECURSIVE_PURE || ForgeContext.STRATEGY.RECURSIVE_PURE) || 
                                     actualStrategy === (forgeContext.STRATEGY?.DOMAIN_BUNDLE || ForgeContext.STRATEGY.DOMAIN_BUNDLE);

    // 2.1. Extract Inlines ("Rellenar el pavo" type files)
    for (const inl of manifest.inlines) {
        const targetAbs = path.resolve(entryDir, inl.normalized);
        const relExt = path.relative(forgeContext.projectRoot, targetAbs);
        const sourceFile = path.resolve(entryDir, inl.raw); // Original source for watermark
        
        // DTS is extracted always
        const shadowDts = vscode.Uri.file(path.join(shadowDir, relExt + '.d.ts'));
        const targetDts = vscode.Uri.file(path.join(forgeContext.projectRoot, relExt + '.d.ts'));
        if (await extractFile(shadowDts, targetDts, false, null, forgeContext.addWatermark, sourceFile)) {
            extractedCount++;
        }
        
        // JS extraction depends on strategy
        if (shouldExtractDependencies) {
            const shadowJs = vscode.Uri.file(path.join(shadowDir, relExt + '.js'));
            const targetJs = vscode.Uri.file(path.join(forgeContext.projectRoot, relExt + '.js'));
            if (await extractFile(shadowJs, targetJs, false, null, forgeContext.addWatermark, sourceFile)) {
                extractedCount++;
            }
        }
    }

    // 2.2. Extract Externals JS if strategy demands it
    for (const ext of manifest.externals) {
        const targetAbs = path.resolve(entryDir, ext.normalized);
        const relExt = path.relative(forgeContext.projectRoot, targetAbs);
        const sourceFile = path.resolve(entryDir, ext.raw); // Original source for watermark

        // DTS is extracted always
        const shadowDts = vscode.Uri.file(path.join(shadowDir, relExt + '.d.ts'));
        const targetDts = vscode.Uri.file(path.join(forgeContext.projectRoot, relExt + '.d.ts'));
        if (await extractFile(shadowDts, targetDts, false, null, forgeContext.addWatermark, sourceFile)) {
            extractedCount++;
        }

        if (shouldExtractDependencies) {
            const shadowJs = vscode.Uri.file(path.join(shadowDir, relExt + '.js'));
            const targetJs = vscode.Uri.file(path.join(forgeContext.projectRoot, relExt + '.js'));
            if (await extractFile(shadowJs, targetJs, false, null, forgeContext.addWatermark, sourceFile)) {
                extractedCount++;
            }

            // Orphan Warning validation!
            if (!(await exists(targetJs))) {
                logger.warn(t('warn.orphan', ext.raw));
                logger.show();
            }
        }
    }

    logger.debug(`[Extractor] Total extracted for ${path.basename(entryFile)}: ${extractedCount}`);
    return extractedCount;
}

module.exports = {
    performExtraction
};
